### ISSUE TITLE
[sled agent] Tracking issue for "better zone death"

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#1600]
- [ ] https://github.com/oxidecomputer/omicron/issues/1597
- [ ] https://github.com/oxidecomputer/omicron/issues/1598
- [ ] https://github.com/oxidecomputer/omicron/issues/1599
