### ISSUE TITLE
Tracking issue for IPv6 support in guests

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/omicron#1716]
This tracks the relevant pieces of getting IPv6 support for guests. There is a bit of blocking work in OPTE which is mostly tracked in https://github.com/oxidecomputer/opte/issues/10. I'll make more issues here as they come up, but for now the list is:

- [ ] Allocate a VPC-private IPv6 address for every guest NIC
- [ ] Support allocation of ephemeral IPv6 addresses out of a pool. This could be a big project. Indexing by IP type might work, or we may need to support only one IP version in any given IP Pool, or change the query / table structure in other ways to make this more efficient. This ties in with #1468 and others.
- [ ] Need to re-check support for IPv6 Router and Firewall APIs
- [ ] Pull in latest OPTE changes to actually assign IPv6 data to guests

**Comment by bnaecker** [comment]
This needs to be updated. The networking implementation has moved a lot since I wrote this. The current blocking issue is #5090, but there may be others. We should find them and update this issue.

OPTE has full support for IPv6 address AFAIK, so I think the main issues are NAT and possibly some API changes to support picking an ephemeral external address of a particular family for a guest.

**Comment by bnaecker** [comment]
This has been done for a while now.
