### ISSUE TITLE
Tracking issue for "Why aren't we ready to demo on SN-XX yet"?

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#1971]
When we've been doing "control plane demos", we have been running through the installation and execution of Omicron from commodity hardware running a Helios image. However, we'd like to migrate to doing these demos on real oxide hardware, like a `gimlet-sn05` scrimlet machine.

This is a tracking issue for "what are all the things blocking the control plane from operating correctly?".

**NOTE**: This is a tracking issue - all the individual issues should be filed in locations where corresponding parts of the team -- possibly not the control plane folks! -- have good visibility and can make progress.

- [ ] [Stopping Switch Zone causes kernel panic](https://www.illumos.org/issues/15167). The control plane has several moments where it wants to initialize and destroy zones (installation, re-initialization of zones [when the underlay becomes available](https://github.com/oxidecomputer/omicron/issues/1961), etc). This issue causes a kernel panic when we tear down the switch zone.
  - [ ] Tracked within https://github.com/oxidecomputer/stlouis/issues/246
- [ ] Time - when we deploy instances and look at metrics, the clock for the machine indicates that it thinks the year is 2000. Note, we don't need synchronized time via something like NTP *quite* yet -- we're still running single-instance CRDB -- but it's jarring to see instances provisioned in the year 2000, and it messes up the web console.\
  - [ ] TODO: NEEDS TRACKING ISSUE
- [ ] ZFS errors, reported https://github.com/oxidecomputer/stlouis/issues/222
  - [ ] This still needs investigation, but I want to confirm that it would not manifest as data errors during a run-through

**Comment by davepacheco** [comment]
Looks like all this was taken care of.
