### ISSUE TITLE
MUP: Build out the installinator

### ISSUE THREAD

**Issue by sunshowers** [oxidecomputer/omicron#2061]
Per [RFD 345](https://rfd.shared.oxide.computer/rfd/0345), the installinator is "[t]he key process in the Phase-2 Trampoline Image that fetches data over the bootstrap network to install on an M-2 device."

> 2.6 Host Phase-2 Install
>
> At the start of this step, the host has booted, it’s running user-land processes, the bootstrap network (and not the underlay network) is available (meaning that T6 and Maghemite are both up). At the conclusion of this step, the Phase-2 Host Image will be present on an M.2 device (of the two).
>
> The Trampoline image contains a single-purpose program called Installinator that downloads the Phase-2 Host Image and places it on an M.2. Installinator discovers peers on the bootstrap network which includes sled-agent and wicketd instances; it connects to each and requests the desired Phase-2 Host Image by ID and/or checksum.
>
> Every sled-agent serves data from its own, current M.2; wicketd serves additional images that have been uploaded to it.

The initial version of the installinator is in #2027. The tasks to be done:

- [ ] Bring up maghemite
  - Do we need to do this within the installinator? The Host Phase-2 Install section quoted above suggests that maghemite is already up when the installinator is run.
- [x] Discover peers on the bootstrap network (done in #2027)
  - [x] Unify discovery API (`ddm_admin_client.rs`) between installinator and sled-agent
- [x] Download data from peers over HTTP (done in #2027)
- [x] Read artifact ID from IPCC
- [x] Add retries and timeouts (done in #2027, with property-based tests)
- [x] Perform validation
  - [x] Checksums?
  - [ ] Signatures?
- [x] Report progress
  - https://github.com/oxidecomputer/minimum-upgradable-product/issues/73
- [x] Figure out destination M.2 to write to
- [x] Write to destination (currently just writes to a file)
  - https://github.com/oxidecomputer/omicron/issues/2361 
- [x] Write end-to-end tests.

And, on the serving end:

- [x] Build out the artifact server that will be shared by wicketd and sled-agent.
  - [x] https://github.com/oxidecomputer/omicron/pull/2106
  - [x] https://github.com/oxidecomputer/omicron/pull/2110
  -  According to @andrewjstone: "Wicket talking to wicketd via wicketd client is probably going to go over [localhost](http://localhost/) for security, and it will eventually have some auth. It almost certainly should not listen on the bootstrap network. However, the get_artifact endpoint used by installinator most definitely should. So yes, this should be a separate server/client, and it can be shared for use by sled-agent."
- [x] Add a way for wicketd to upload artifacts to the artifact server
- [ ] Add a way for sled-agent to serve artifacts from its own M.2.

**Comment by sunshowers** [comment]
The installinator has shipped and is in pretty good shape (#3507 notwithstanding). Closing now.
