### ISSUE TITLE
Tracking issue for initial System Update API

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/omicron#2107]
[RFD 322 System Update API](https://rfd.shared.oxide.computer/rfd/0322) outlines the external API but leaves the internals unspecified. #250 is a tracking issue with great detail on the internals. Initial API work is happening in #2100.

- [ ] Endpoints according to RFD 348
  - [x] Get current system update status (version range + updating or steady) #2038 
  - [x] Get tree of component statuses/versions
  - [x] List available updates #2039
  - [x] Get system update by version string
  - [x] Get component updates for system update
  - [ ] Update dry run/impact summary #2040 
  - [x] Start update
  - [x] Stop update
  - [x] List update deployment history (update runs)
- [ ] DB tables
  - [x] System updates
  - [x] Component updates + assoc with system updates
  - [x] Updateable component versions + status
  - [x] Update deployments w/ status/outcome
  - [x] Store semver versions in DB as a string with proper ser/de into `semver::Version`
  - [x] Enforce uniqueness of semver version
- Connection to underlying systems
  - [ ] TUF repo scan populates `system_update` and `component_update` tables (original PR: #717)

**Comment by david-crespo** [comment]
Marking this completed as a kind of phase 1 and make a new tracking issue for the remaining work.
