### ISSUE TITLE
Wicket: Tracking Issue

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#2213]
- [x] #1871 (also: see [this issue](https://github.com/oxidecomputer/minimum-upgradable-product/issues/32))
- [x] [Wicket must ensure sshd is automatically launched](https://github.com/oxidecomputer/minimum-upgradable-product/issues/20)
- [x] Wicket must provide TUI over ssh as captive shell
- [x] Wicket must identify sleds and present them over the TUI
- [x] #2214
- [x] Wicket TUI must allow user to select one or more sleds for recovery
- [x] #1868
- [x] Wicketd must accept packages, transferred from laptop via technician port
  - [x] Provide a way to upload packages via wicket: https://github.com/oxidecomputer/omicron/pull/2165
  - [x] Interpret packages as TUF repositories
    See also: https://github.com/oxidecomputer/minimum-upgradable-product/issues/71
- [x] [Wicketd must send packages to MGS to trigger updates
](https://github.com/oxidecomputer/minimum-upgradable-product/issues/23)
- [ ] #2216
- [x] #2217
- [x] #2218

**Comment by sunshowers** [comment]
Done for FCS.
