### ISSUE TITLE
Tracking issue for NTP Integration

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#2219]
- [ ] Choose an NTP daemon (maybe chrony?)
  - [ ] Package NTP daemon as a zone
  - [ ] Figure out client & server NTP configuration (e.g., handling of leap seconds)
- [ ] Every Gimlet: Spin up zone running NTP daemon (probably launched by sled agent)
- [ ] On Scrimlet: Also spin up zone running NTP server
  - [ ] See also: Wicket issue for configuration handoff
  - [ ] See also: Configuration information for NTP should be transferred through Nexus to CRDB
- [ ] Updates to NTP configuration should be possible through Nexus API
  - [ ] Updating NTP configuration should push changes to all servers that need it
  - [ ] Also update network configuration related to NTP (accessibility to NTP server outside rack). E.g. Update zone's network access, dendrite rules for external networking.
- [ ] Pushing upstream NTP configuration to virtual machines.
  - [ ] (MVP + 1): We'd like to use the per-sled NTP daemon as the VM's NTP server...
  - [ ] (MVP): ... But if that's too much, we just need to plumb *something* - we can point them at the same NTP server used by the whole rack.
    - [ ] Related; we really just need to be consistent about "which NTP server we use" - they can differ with details like implementation of leap second smearing, which could result in inconsistent time if desynchronized. 
- [ ] TBD: How are we bootstrapping the address discovery here? Probably want to use an AZ-wide subnet (similar to DNS) and post up the Scrimlet services on a well-known address.
