### ISSUE TITLE
Tracking: System Update API (phase 2)

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/omicron#2341]
See #2107 for phase 1 tracking issue and #2100 for most of the code. That work was about setting up the endpoints and the underlying data model without much reference to the actual TUF repo and update artifacts or the update planner. The updates we display in the console is mock data added in #2283 and #2294. 

This issue tracks work around replacing that mock data with real data by populating the update tables from the TUF repo and the component version from the actual installed software present in the rack. See #250 for the work on the underlying systems and planner.

```[tasklist]
- [ ] https://github.com/oxidecomputer/omicron/issues/2344
- [ ] https://github.com/oxidecomputer/omicron/issues/2040
- [ ] https://github.com/oxidecomputer/omicron/pull/2834
- [ ] https://github.com/oxidecomputer/omicron/issues/2838
- [ ] Combine UpdateArtifact and ComponentUpdate, they are the same thing
- [ ] Sort update deployments by `time_created` desc (requires #2343)
- [ ] https://github.com/oxidecomputer/omicron/issues/766
```

**Comment by davepacheco** [comment]
I believe this needs we ripped most of this out already and need to add new APIs for this.  I expect we'll file new issues for that.  (Please feel free to reopen if I'm wrong!)
