### ISSUE TITLE
Trust Quorum -> Storage Unlock

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#251]
## Context
- [RFD 90: Rack-Level Boot Sequence](https://rfd.shared.oxide.computer/rfd/0090)
- [RFD 194: Control Plane Membership, Failure Detection, and Service Discovery](https://rfd.shared.oxide.computer/rfd/0194)

## Background

The bootstrap agent, as implemented, is being a bit of a slacker:

https://github.com/oxidecomputer/omicron/blob/96cb81fef84b2f418a5eabfaf32b0569b05d4e56/omicron-bootstrap-agent/src/bootstrap_agent.rs#L72-L78

In reality, the bootstrap agent needs to have a much more significant role of discovering + coordinating with other bootstrap services to establish a shared secret and unlock local storage.

The scope here is broad - and this issue should likely be split into smaller tracking issues - but we can consider this high-level issue complete when bootstrap agents are capable of establishing a shared secret, unlocking local storage, and proceeding to the next step of the boot sequence.

## Tasks

- [ ] Define an interface for interacting with the SP/RoT to perform key management
- [ ] Implement mechanism for bootstrap agent discovery
- [ ] Implement key threshold secret bootstrapping (initialization)
- [ ] Implement key threshold secret sharing (joining + unlocking)
- [ ] Unlock local storage after reaching secret threshold
- [ ] Update CockroachDB SQL tables to store necessary membership information (this is mentioned in RFD 194; full scope TBD)

**Comment by andrewjstone** [comment]
I'm gonna close this and call it done now that LRTQ is merged and working on dogfood. I think separate issues should be opened for specifics of later versions of the trust quorum protocol. Really though, I want to get back to updating the relevant RFDs before that.
