### ISSUE TITLE
Wicket styling tracking issue

### ISSUE THREAD

**Issue by andrewjstone** [oxidecomputer/omicron#2560]
- [ ] Dim green is hard to see when used for text. A new color or two would be nice. Yellow and purple is not my fav combo.
- [ ] All capital letters are hard to read for dyslexics.
- [ ] Component status for updates should be displayed for the top level rack component in the tree,  even when closed.
    - [ ]  We should use colors for this
    - [ ] We should add a custom indicator character in front of the component name for each state for those who are colorblind

**Comment by benjaminleonard** [comment]
>  Dim green is hard to see when used for text. A new color or two would be nice. Yellow and purple is not my fav combo.

Sounds good, I've got a blue too — but I can also just work on some new ones.

>  All capital letters are hard to read for dyslexics.
Np

Do you mind expanding on: "Component status for updates should be displayed for the top level rack component in the tree, even when closed."? I don't fully understand.

> We should style components when they are present but unavailable. Style by power state?
It does start to get challenging since we don't want to represent state just with colour as you know since it's not accessible. I'll take a look, maybe the face of the component is a dashed line or something when it's not present.

**Comment by andrewjstone** [comment]
> Do you mind expanding on: "Component status for updates should be displayed for the top level rack component in the tree, even when closed."? I don't fully understand.

Sorry, this was mainly for myself. If you look at the picture (ignore the experimental purple at the bottom - although, possibly using it for the angle brackets with bright green for keys would look nice :) ) you'll see that `Sled0`, `Sled1`, etc... are all white whether the subtree is expanded or collapsed. For a broad overview of update state I'd like to style these so you don't have to open each subtree and scroll.

![Screen Shot 2023-03-15 at 1 49 26 PM](https://user-images.githubusercontent.com/466937/225398511-e4ac918f-88ef-467b-83d5-dbe1830bcb34.png)

**Comment by andrewjstone** [comment]
> It does start to get challenging since we don't want to represent state just with colour as you know since it's not accessible. I'll take a look, maybe the face of the component is a dashed line or something when it's not present.

That's a really interesting idea. Thanks for taking a look!
