### ISSUE TITLE
Tracking Issue for Managing CPU & RAM Capacity

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#2648]
See also: RFD 380

- [ ] Track provisioned CPU and RAM to services and instances on a per-sled basis in CRDB
- [ ] Apply constraints to limit usage on a per-zone basis
- [ ] Use this information as a factor in sled selection for services and instances
- [ ] Add metrics to periodically monitor true CPU and RAM utilization by services within the sled

#1700 is a similar issue, but for disk space

**Comment by gjcolombo** [comment]
Latest on this:

- RFD 413 on memory governance is ready for one last once-over before publishing
- Once it is published I will create a project plan for the work it describes
- I'll then create issues to track those work items
- We also need an RFD talking about CPU governance; I'm undecided as to whether to do that in RFD 395 or write something else (leaning very vaguely toward the latter). I expect that RFD to be less complex and believe that a good deal of the work we do for memory governance will be extensible to CPU governance (provided we play our cards right).
