### ISSUE TITLE
Tracking issue for USDT Integration

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#298]
https://crates.io/crates/usdt is super sick, and it's about time we start integrating! This issue tracks integration into a variety of potential spots within omicron:

- [ ] Sled Agent (device management)
- [ ] Sled Agent (interfacing w/Propolis)
- [ ] Sled Agent's bootstrapping
- [ ] Nexus (APIs)
- [ ] Nexus (DB) interface
- [ ] ... other?

**Comment by bnaecker** [comment]
The database-related probes, for connections and queries, has been implemented as part of #488.

**Comment by bnaecker** [comment]
Log messages are emitted to DTrace as part of #489.

**Comment by jordanhendricks** [comment]
I have been looking through issues to find things related to development and debugging. Can this one be closed?

**Comment by bnaecker** [comment]
I think we've gotten a good core of probes, and hopefully folks find it easy enough to add more. I'll close this now, thanks @jordanhendricks.
