### ISSUE TITLE
Tracking issue for adding "Users" and "Organizations" to API, database

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#299]
https://rfd.shared.oxide.computer/rfd/0044 has more detail, but the TL;DR is:

- We already have "Projects" within the API/repository, but we have neither "Organizations" nor "Users".
- There is a lot of follow-up work to actually *use* these values, in particular with IAM, billing, active directory integration, etc.

 I have detailed the necessary steps to add these endpoints, attempting to over-document to make this a viable starter project.

(edit: and to clarify - I'm happy to add more detail wherever it would be useful! :grin: )

Completing this issue should make someone familiar with running Omicron, modifying the database, and extending the externally-visible API endpoints.
- [x] Extend the API...
  - [ ] ... with externally-visible "User" structure within https://github.com/oxidecomputer/omicron/blob/main/common/src/api/external/mod.rs
  - [x] ... with externally-visible "Organization" structure
  - [x] ... add a [dropshot](https://crates.io/crates/dropshot) endpoint to create/update/delete users within Nexus: https://github.com/oxidecomputer/omicron/blob/main/nexus/src/http_entrypoints_external.rs
  - [x] ... add a similar endpoint for organizations
  - [x] ... extend Projects to be related to Organizations (#308)
- [x] Update the database to store these values...
  - [x] ... within our SQL definition: https://github.com/oxidecomputer/omicron/blob/main/common/src/sql/dbinit.sql
  - [x] ... as well as the Rust query builder: https://github.com/oxidecomputer/omicron/blob/main/nexus/src/db/model.rs
  - [x] ... and exposing method for Nexus to add and remove users and organizations: https://github.com/oxidecomputer/omicron/blob/main/nexus/src/db/datastore.rs
- [x] Test the new endpoints...
  - [x] ... by updating the "oxapi_demo" script to poke at these new methods, and eyeball that things work
  - [x] ... and add an automated test (going through the CRUD lifecycle) within Nexus: https://github.com/oxidecomputer/omicron/tree/main/nexus/tests
