### ISSUE TITLE
Tracking issue for configs that could cross version boundaries

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#3704]
https://github.com/oxidecomputer/omicron/issues/3703 and https://github.com/oxidecomputer/omicron/issues/3407 are related to this.

- [ ] Service ledger - `services.toml` (stored in the config dataset to allow the sled agent to re-instantiate servics)
- [ ] Zone bundle Metadata - `metadata.toml` (stored in the config dataset to track debug bundles)
- [ ] Nexus's configuration file, which is processed and created by the sled agent  - (constructed dynamically while creating the Nexus zone)
- [ ] The bootstrap's notion of "how to launch the sled agent" - `sled-agent-request.toml` 
- [ ] The Rack Setup Service's sled and service plans: `rss-sled-plan.toml`, `rss-service-plan.toml`
- [ ] Any configs added by @andrewjstone 's bootstore PRs
