### ISSUE TITLE
Tracking issue: move views and params out of common

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/omicron#388]
This is meant to capture the substantial followup work based on #369, #374, and #386.

Now that we have generated clients for internal communication, each app should own the structs that define its request bodies (params) and responses (views). The difficulty is that there are a lot of changes to be made before we reach the desired end state, way more than would be reasonable to put in a single PR. Refactors should be done as quickly as possible, but there's going to be a short time where we're in an intermediate state. Also doing a bunch of refactors while we're all hurrying for Milestone 3 is not a good idea. So we're going to have to finish this afterward.

- [ ] Simple public views only used in Nexus
  - [x] `Project` and `Organization` (done in #374)
  - [ ] `Vpc` and friends
- [x] Sled agent things
  - [x] `DiskEnsureBody`, `DiskStateRequested`, `ShareRequest`, `ShareResponse` (done in #386)
  - [x] [`InstanceHardware`, `InstanceEnsureBody`](https://github.com/oxidecomputer/omicron/blob/9f6cfcc36251fb0ab1ecdd690132e6e3e57bf712/common/src/api/internal/sled_agent.rs#L42-L57), `InstanceRuntimeStateRequested`
- [ ] Runtime state things
  - [ ] [`DiskRuntimeState`](https://github.com/oxidecomputer/omicron/blob/9f6cfcc36251fb0ab1ecdd690132e6e3e57bf712/common/src/api/internal/nexus.rs#L16) — kind of interesting because both nexus and sled agent have endpoints that use this struct. this means they should probably each own their own and define a conversion to the other's. There's also the fun fact that Nexus stores this in the db. lots of lines in the diff because it's used in like 60 places
  - [ ] [`InstanceRuntimeState`](https://github.com/oxidecomputer/omicron/blob/9f6cfcc36251fb0ab1ecdd690132e6e3e57bf712/common/src/api/internal/nexus.rs#L30) — same deal

This is not a complete list, I'll add more as I go through them.

**Comment by david-crespo** [comment]
> there's going to be a short time where we're in an intermediate state

welp

**Comment by david-crespo** [comment]
I spent a little time trying to move [`RouterRoute` and its params friends](https://github.com/oxidecomputer/omicron/blob/c66d2f6d47823a3b38b6b983a0380866e97ef362/common/src/api/external/mod.rs#L1248-L1281) into Nexus, but it was quite difficult to untangle what should go where. They all depend on the enums [`RouteTarget`](https://github.com/oxidecomputer/omicron/blob/c66d2f6d47823a3b38b6b983a0380866e97ef362/common/src/api/external/mod.rs#L1171) and [`RouteDestination`](https://github.com/oxidecomputer/omicron/blob/c66d2f6d47823a3b38b6b983a0380866e97ef362/common/src/api/external/mod.rs#L1203), which are also used in several other places.

I also spent a bit of time attempting [`UpdateArtifact` and `UpdateArtifactKind`](https://github.com/oxidecomputer/omicron/blob/c66d2f6d47823a3b38b6b983a0380866e97ef362/common/src/api/internal/nexus.rs#L80-L97), but in this case the complication comes from it being used in both Sled Agent and Nexus. I think this should be defined in Nexus and then Sled Agent should mostly rely on the types from the generated Nexus client, but I had trouble making this compile because of the interdependent macros (sled agent client gen and nexus client gen).

This is emblematic of the situation with the remaining views.

**Comment by david-crespo** [comment]
I think we got as far as we're going to get on this.
