### ISSUE TITLE
Tracking issue for adding a sled to an existing rack cluster

### ISSUE THREAD

**Issue by andrewjstone** [oxidecomputer/omicron#3924]
See https://rfd.shared.oxide.computer/rfd/0417

- [x] Hardware Sled discovery
    - [x] Add rack_id to MGS via SMF property
    - [x] Add a new `hardware_sled` table to the CRDB schema
    - [x] Add ability to retrieve uninitialized sleds from Nexus public API by reading CRDB and diffing sled/hardware_sled tables
    - [x] Have Nexus Poll MGS for new sleds and add them to `hardware_sled` table
- [x] Adding an uninitialized sled
    - [x] Ability to trigger addition of new sled to the cluster via Nexus public API
    - [x] Nexus to local sled-agent API
    - [x] sled-agent to bootstrap agent API
    - [x] bootstrap agent handling/bootstore learner node config

**Comment by andrewjstone** [comment]
`rack_id` added to MGS SMF in https://github.com/oxidecomputer/omicron/pull/4145

**Comment by andrewjstone** [comment]
Final PR is out here: https://github.com/oxidecomputer/omicron/pull/4545
