### ISSUE TITLE
Tracking Issue for Database Improvements

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#4189]
Tracking issue for improvements interacting with the database. Please edit and add issues accordingly.

## Async

- [ ] https://github.com/oxidecomputer/omicron/issues/4188

## Pools

- [x] #4192
- [ ] https://github.com/oxidecomputer/omicron/issues/4191

## Transactions & CTEs

- [x] https://github.com/oxidecomputer/omicron/issues/3814
- [x] https://github.com/oxidecomputer/omicron/issues/3304
- [ ] https://github.com/oxidecomputer/omicron/issues/4190
- [ ] https://github.com/oxidecomputer/omicron/issues/973

## Updates

- [ ] https://github.com/oxidecomputer/omicron/issues/210
- [ ] (Related to #210) Audit usage of `SELECT *` and `RETURNING *`, prefer explicit columns so we access columns consistently across updates

## Safety

- [ ] https://github.com/oxidecomputer/omicron/issues/4144
- [ ] https://github.com/oxidecomputer/omicron/issues/1168
- [ ] https://github.com/oxidecomputer/omicron/issues/263

## Ergonomics

- [ ] https://github.com/oxidecomputer/omicron/issues/312
