### ISSUE TITLE
Tracking Issue: Resource Allocation (Silo)

### ISSUE THREAD

**Issue by morlandi7** [oxidecomputer/omicron#4554]
Ability to limit (and view) the amount of resources allocated to each silo to enable multi-tenancy without running the rack out of resources. 

```[tasklist]
### Tasks
- [x] Flesh out RFD https://rfd.shared.oxide.computer/rfd/0427
- [ ] Do the work https://github.com/oxidecomputer/omicron/pull/4605
- [ ] Create tracking issue to plan for project level resource allocations if needed
```
Customer issue reference:  https://github.com/oxidecomputer/customer-support/issues/21
