### ISSUE TITLE
Capacity, utilization, and resource limits tracking issue

### ISSUE THREAD

**Issue by zephraph** [oxidecomputer/omicron#4751]
This is mostly an issue for myself to track the remaining work around cap, util, and quotas. 

```[tasklist]
- [ ] impl `system_utilization_view` for top level `provisioned`, `allocated`, and `capacity` numbers
- [ ] Add sled level utilization views
- [ ] Add IP quotas
- [ ] Update cap & utilization with IP quotas
```

## Related issues

- https://github.com/oxidecomputer/product-assurance/issues/11
  - tracks some capactiy and utilization work
- https://github.com/oxidecomputer/omicron/issues/2036

**Comment by twinfees** [comment]
Noting here that a customer has reported the confusing `10B` quota that is displayed for CPU from the `Utilization` tab from the web console.

**Comment by david-crespo** [comment]
Assuming that's because the default silo is showing up there, I think that would be solved by https://github.com/oxidecomputer/omicron/issues/5731, which I'm going to prioritize for the next release.

**Comment by david-crespo** [comment]
@morlandi7 @askfongjojo I lean toward closing this because the only hard issue it points to is #5731. I think the items in the checklist are not priorities. Per-silo IP quotas can be achieved by using separate IP pools. It's not amazing but it works.

https://github.com/oxidecomputer/omicron/issues/2036 and https://github.com/oxidecomputer/product-assurance/issues/11 are themselves each tracking issues that could stand to be cleaned up.

**Comment by askfongjojo** [comment]
I think the IP pool utilization aspect is still important, i.e. how many IP addresses are used vs available for my silo. Maybe we can update this ticket for just that as the scope.

**Comment by david-crespo** [comment]
Created #8459
