### ISSUE TITLE
Physical Disk Lifecycle: Tracking Issue

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#5149]
This is a tracking issue for a few related issues I'm actively working on regarding Physical Disk lifecycles.

In broad terms, we need to do the following:
- Decouple the notion of a "control plane physical disk" from a "physical disk in inventory". They're currently overloaded in the single "Physical Disk" database table, upserted by sleds through the Nexus API, but need to be decoupled to properly manage their lifecycles.
- Allow Nexus to control more of the U.2 storage explicitly, so it can understand the fall-out of expunging disks.
- Refactor "when disks are actually being formatted" within the Sled Agent, and defer this process until their corresponding "Control plane objects" are created.
- Provide opportunities for Nexus to answer ambiguous questions about disks, like "should a new disk be adopted by the system", or "what do we do with a U.2 that has non-conforming partitions"?

Some additional background context can be found on https://github.com/oxidecomputer/rfd/pull/712 , which is an addendum to RFD 457.

In specific issues:

- [x] #5150: We need to know physical disks exist in Nexus before they can be processed further.
- [x] #5151: Once we know physical disks exist, we can manage their lifecycle explicitly. This will also change interactions with RSS, which will probably need to also take control of this provisioning too.
- [ ] #5152: Once Nexus can provision new physical disks, it can also take charge of decisions like "what do we do with weirdly-formatted disks".
- [x] #5048: This is a pre-requisite for knowing "what could die when we expunge a disk"
- [x] #5153: These are the levers to actually initiate the expungement process 
- [x] #5154
- [x] #5155
- [x] https://github.com/oxidecomputer/omicron/issues/5328
- [x] #5369
- [x] #5370
- [x] https://github.com/oxidecomputer/omicron/issues/5372

**Comment by davepacheco** [comment]
@smklein is #5150 the only remaining issue here?

**Comment by smklein** [comment]
As far as I know. I can close this larger issue and track #5150 separately, if you want?

**Comment by davepacheco** [comment]
Sure!
