### ISSUE TITLE
[sled-agent] Tracking issue for "test it in a VMM"

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#5329]
Once https://github.com/oxidecomputer/omicron/pull/5285 merges, we will have the ability to write tests for the illumos target which can execute within a VMM, and which can assume exclusive access to the underlying machine.

This will be a boon for tests which wish to, for example, modify storage, configs, etc.

This issue tracks tests which should be converted:

- [ ] Pretty much all tests using the `StorageManagerTestHarness`, from https://github.com/oxidecomputer/omicron/pull/5172. This harness creates zpools from files in `/var/tmp`, but doesn't perform the best cleanup in certain test failures.
- [ ] sled-agent/src/services.rs -- uses a lot of mocks, shouldn't
- [ ] sled-agent/src/instance.rs -- relies on mocks, ideally wouldn't
- [ ] sled-agent/src/dump_device.rs -- uses fakes, but could use "real disks" from the VMM

There are additional spots where test coverage would be beneficial, but for which tests don't currently exist, including:

- [ ] sled-agent/src/swap_device.rs
- [ ] sled-agent/src/backing_fs.rs
- [ ] sled-agent/src/vmm_reservoir.rs
