### ISSUE TITLE
Reconfigurator: Tracking issue for multi-node clickhouse deployment

### ISSUE THREAD

**Issue by andrewjstone** [oxidecomputer/omicron#5999]
This is a tracking issue for all the work related to deploying multi-node clickhouse on a running system via reconfigurator. We expect that each system will run both single and multi-node for a while per [RFD 468](https://rfd.shared.oxide.computer/rfd/0468) and reconfigurator should allow us to transition between the two at runtime. We likely will need to change RSS to also deploy single and multi-node clickhouse to support this.

Reconfigurator:

- [x] #6298
- [x] #6299
- [x] Add CRDB blueprint tables related to clickhouse configuration
- [x] Add planner code for deploying single node and multi-node clickhouse
    - [x] Add logic and tests to generate a configuration - `ClickhouseAllocator`
    - [x] Integrate `ClickhouseAllocator` into blueprint and db queries
- [x] Add planner code for enabling multi-node clickhouse
- [x] Add clickhouse configuration to RSS service plan (or punt to reconfigurator)
- [x] Add executor code to deploy single and multi-node clickhouse
- [x] Add executor code to enable multi-node clickhouse
- [x] Add omdb support for reconfigurator deployment of clickhouse
- [x] Add omdb support for inspection/debugging of clickhouse
    - [x] [keeper membership in inventory](https://github.com/oxidecomputer/omicron/pull/6950)
    - [x] [blueprint support for cluster membership](https://github.com/oxidecomputer/omicron/issues/6941)
    - [x] [General Debugging support](https://github.com/oxidecomputer/omicron/issues/6953)

Sled-agent:

- [x] Create new `clickhouse_server` zone and move all replicated clickhouse related code there https://github.com/oxidecomputer/omicron/pull/6343
- [x] Generate clickhouse XML configs with clickward instead of shell scripts https://github.com/oxidecomputer/omicron/issues/3824
- [x] Mechanism to deploy either replicated or single node clickhouse https://github.com/oxidecomputer/omicron/pull/6343
- [x] Deploy 3 server 5 keeper cluster instead of the current 2 server 3 keeper cluster
- [x] Dropshot service to manage clickhouse server or keeper nodes https://github.com/oxidecomputer/omicron/pull/6304

Oximeter:

- [x] Make it possible for oximeter to read/write to a clickhouse cluster https://github.com/oxidecomputer/omicron/issues/7338

**Comment by karencfv** [comment]
Related https://github.com/oxidecomputer/omicron/issues/6407

**Comment by karencfv** [comment]
Closed by https://github.com/oxidecomputer/omicron/pull/7522
