### ISSUE TITLE
[sled-agent] Tracking issue for Bootstrap Agent / Sled Agent / RSS re-work

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#824]
The intent of this issue is to track the issues necessary to align the bootstrapping process with what has been described by [RFD 259](https://github.com/oxidecomputer/rfd/tree/0259/rfd/0259).

- [ ] Bootstrap Agent
  - [ ] https://github.com/oxidecomputer/omicron/issues/820
  - [ ] https://github.com/oxidecomputer/omicron/issues/821
  - [ ] https://github.com/oxidecomputer/omicron/issues/822
  - [ ] https://github.com/oxidecomputer/omicron/issues/823
- [ ] Nexus
  - [ ] https://github.com/oxidecomputer/omicron/issues/732

**Comment by rcgoodfellow** [comment]
CC'ing myself so updates show up in my GH feed @rcgoodfellow
