### ISSUE TITLE
tracking issue for MVP IAM work

### ISSUE THREAD

**Issue by davepacheco** [oxidecomputer/omicron#849]
([Original source](https://docs.google.com/document/d/1H9b2egM4WlmAF7Sjx0xa3cvhxqNYB4saygxp2vUpEnw/edit#heading=h.jb00tci79w86).  NOTE: some of the work in that doc is not part of Omicron (e.g., RSS parts) and so isn't mentioned here.)

NOTE: Unless a bullet item says otherwise, it's talking about support in Nexus and the API, _not_ support in the CLI and console.  CLI and console support are covered in separate bullet points towards the bottom.

- [x] Initial Silos work
    - [x] #814
    - [x] #850 / #937
- [x] support for assigning roles to Silo users and resources
    - [x] #890
    - [x] #1002
    - [x] #1042
    - [x] #1044
    - [x] #1051
- [x] ssh key management
    - [x] #954
    - [x] #974
- [ ] Integration with customer IDP
    - [x] #1139
    - [x] #1210 (includes JIT provisioning (auto-create users on SAML login) and SAML login flow)
    - [x] #1358
    - [ ] #3527
    - [ ] #3528
    - [ ] ~~Test with PingFederate~~
- [x] #1699
    - [x] #1784
    - [x] #1841 
- [x] #2943
- [ ] users/groups APIs: read-only for SAML Silos, plus maybe "delete" for administrators
  - [x] #1261
  - [x] #1784
  - [ ] #1209
  - [ ] #2051
- [ ] Device (CLI, API) authn:
  - [x] #1194
  - [ ] #2302
  - [ ] #2306
- [ ] ~~service accounts~~
- [ ] silo login flow, console and API DNS names
    - [x] #2918
    - [ ] #3529
    - [x] console needs a password login page for "local only" Silos (#3217 / oxidecomputer/console#1533)
- [ ] Console support for above features
    - [x] role assignments for Organization and Project
    - [ ] role assignments for Fleet and Silo
    - [x] ssh keys
    - [ ] Silos, IdP setup
- [ ] CLI support for above features
    - [x] oxidecomputer/cli#221
    - [x] oxidecomputer/cli#219
    - [x] https://github.com/oxidecomputer/cli/issues/34
- [x] resolve #1354
- [ ] all of authz, tracked under #419
- [ ] #1340
    - [x] #1580 
    - [ ] #1681
    - [ ] Depending on the outcome of 1681, enforce that Silo, Organization, and Project policies cannot refer to identities outside the Silo.  See #1580. (edit: updated 1681 to include this)
    - [ ] Depending on the outcome of 1681, disallow fleet administrators from reading or modifying the policy on the Silo.  See #1580 for details.  Since fleet admins need to be able to modify which group is the "admin" group for a Silo, they may wind up changing the policy, but would not have carte blanche to change it however they like.  (edit: updated 1681 to include this)
- [x] #3275
- [ ] cleanup / bugs
    - [x] #1080
    - [x] #1087
    - [x] #1090
    - [x] #1110 
    - [x] #1112 
    - [x] #1113
    - [ ] #1332
    - [ ] #1185
    - [ ] decide whether we want to change "Fleet" in the authz subsystem to something else ("global", "region", or "az?).  The way it's used is more like "az" or "region" but it's not yet clear which.  This is most important for when roles are assigned on this resource -- everything else we could presumably change later, but that's going to be stored in the database.
    - [ ] authz check for modifying resource policy needs work
    - [ ] consider revisiting policy representation -- see considerations raised in #890
    - [ ] consider whether we ought to re-work the schema for roles and role assignments with an eye towards custom roles in the future.  For example, we might use uuids to identify roles (rather than `(resource_type, role_name)` tuple) in the `role_assignments` table
    - [ ] audit the exemption list in the role policy test
    - [ ] #2305

CC @jmpesp what have I missed?

**Comment by david-crespo** [comment]
Do any of these bullets represent being able to list users in a group? I don't see one.

Say you're on a project access page and some group has read access on that project. I would want to be able to click on the group and see who is in it. While we're using the JIT model for users, this list would necessarily be limited to users we're aware of because they've logged in. That might be confusing if there's a user you expect to see because you know they're in the group on the IdP side, but they don't show up because they've never logged into Oxide.

**Comment by davepacheco** [comment]
Good call.  I don't think there was anything there that covered that.  I added this as "list users in groups, list groups associated with a user".

> While we're using the JIT model for users, this list would necessarily be limited to users we're aware of because they've logged in. That might be confusing if there's a user you expect to see because you know they're in the group on the IdP side, but they don't show up because they've never logged into Oxide.

Yup.  I don't think there's much we can do in the API to mitigate this but maybe we can do something in the console?  e.g., a small "expecting to see somebody else here?" link to a help page?

**Comment by david-crespo** [comment]
Right, good idea. We can at least explain it.

**Comment by benjaminleonard** [comment]
We need an unauthed endpoint that returns a silo's display name and its associated IdPs to implement the login screen on console. We do need to know which silo you're in right? Will this get unblocked when we have subdomains for silos?

**Comment by davepacheco** [comment]
> We need an unauthed endpoint that returns a silo's display name and its associated IdPs to implement the login screen on console. We do need to know which silo you're in right? Will this get unblocked when we have subdomains for silos?

Yeah, Silos already have their own DNS names, though people don't necessarily use them in development.  In a real system, we'll know which Silo you're in based on the DNS name you came in through (really the TLS SNI name, but those are generally the same thing).  I'm not yet clear on what we'll do in development for this, where people often aren't using TLS nor DNS.

Even though we should know the Silo name already, for SAML, login starts when you `GET /login/{silo_name}/saml/{idp_name}` and ends with `POST /login/{silo_name}/saml/{idp_name}`.  For password login, it ends with `POST /login/{silo_name}/saml`.  So I figured we'd serve the password login page at `GET /login/{silo_name}/local` and we'll know where to `POST` the credentials.  For SAML, we at least discussed having redirects so that `GET /login/{silo_name}/saml` redirects you to the `GET` for some default IdP.  We could also have redirects from `GET /login`, since we should know the silo name already.  I think these shouldn't be blockers?  What do you think?

**Comment by davepacheco** [comment]
> As I understand it, multiple IdPs on a single silo is uncommon but also trivial to support with this UI:

Yeah, as I understand it, it would be easy from the UI perspective.  It's nasty internally and we want to avoid it (see all the stuff in RFD 234).  I can still see it being useful to see a landing page like that, though, so you know what you're even logging into.

> If we had those then the minimum we could return to serve this page would be: `silo_name` (which we already have and just need to make accessible without being authed) and associated `idp_name[]`.

I'm not sure how best to convey these.  @david-crespo or @zephraph have thoughts about all this?

> For dogfood would be move everything over to the IdP silo? So we don't have two silos on a single DNS name?

Yeah...I believe that right now, we have a DNS "A" record that points the dogfood DNS name to the Nexus IP.  It works in terms of TLS for whatever Silos we've uploaded that certificate for.  But it's working a little bit by accident because we haven't finished this work.  Nexus doesn't know what Silo you're coming in for in that configuration.  It just doesn't care because it doesn't use that information yet.

(Another reason we don't want customers to do this is that we want to be in charge of DNS so that we can change IPs if we need to.  At some point I think we want to change the dogfood DNS name to be a CNAME for the DNS name provided by the rack's own external DNS server.  I think that's mostly unrelated, though.)

In order to keep using the same DNS name for Dogfood, we'll have to implement support for what I'd call "DNS aliases", where you can specify that the rack should serve one Silo's endpoints (e.g., "the-silo.sys.some-internal-dns-name.example") at some other DNS name (e.g., "the-silo.company.example").  I believe this is *not* needed for FCS so we'll have to decide whether we want to do this feature anyway and use it in Dogfood or change the Dogfood DNS name to just use the rack-provided naming scheme.

**Comment by davepacheco** [comment]
I've created issues for the open non-cleanup items so I think we can close this one.

@benjaminleonard I think we ended up addressing what you wanted?
